#!/usr/bin/env bash
# render package-manager manifests from a verified release directory.
set -euo pipefail

usage() {
    cat >&2 <<'EOF'
usage: prepare-packages.sh --dist DIR --version VERSION --output-dir DIR

The release directory must contain the macOS DMG, Linux x86_64 archive, both
Windows installers, and a checksums.txt generated by checksums.sh. The output
directory receives Homebrew, AUR, and winget files ready to copy upstream.
EOF
    exit 2
}

fail() {
    echo "prepare-packages.sh: $*" >&2
    exit 1
}

dist=''
version=''
output_dir=''

while (($# > 0)); do
    case "$1" in
        --dist|--version|--output-dir)
            [[ $# -ge 2 ]] || usage
            case "$1" in
                --dist) dist=$2 ;;
                --version) version=$2 ;;
                --output-dir) output_dir=$2 ;;
            esac
            shift 2
            ;;
        *)
            usage
            ;;
    esac
done

[[ -n "$dist" && -n "$version" && -n "$output_dir" ]] || usage
[[ "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || {
    fail "package manifests require a stable semantic version: $version"
}
[[ -d "$dist" ]] || fail "release directory does not exist: $dist"

dist="$(cd "$dist" && pwd)"
mkdir -p "$output_dir"
output_dir="$(cd "$output_dir" && pwd)"
checksum_file="$dist/checksums.txt"
[[ -f "$checksum_file" ]] || {
    fail "missing checksums.txt in release directory: $dist"
}

sha256_for() {
    local path=$1
    if command -v sha256sum >/dev/null 2>&1; then
        sha256sum "$path" | awk '{ print $1 }'
    elif command -v shasum >/dev/null 2>&1; then
        shasum -a 256 "$path" | awk '{ print $1 }'
    else
        fail 'sha256sum or shasum is required'
    fi
}

checksum_for() {
    local filename=$1
    local count digest expected
    count="$(awk -v wanted="$filename" '$2 == wanted { count++ } END { print count + 0 }' "$checksum_file")"
    [[ "$count" == 1 ]] || {
        fail "checksums.txt must contain exactly one entry for $filename"
    }
    digest="$(awk -v wanted="$filename" '$2 == wanted { print $1; exit }' "$checksum_file")"
    [[ "$digest" =~ ^[[:xdigit:]]{64}$ ]] || {
        fail "invalid SHA-256 for $filename in checksums.txt"
    }
    digest="$(printf '%s' "$digest" | tr '[:upper:]' '[:lower:]')"
    expected="$(sha256_for "$dist/$filename")"
    [[ "$digest" == "$expected" ]] || {
        fail "checksum mismatch for $filename"
    }
    printf '%s\n' "$digest"
}

macos_asset="woofer-v${version}-macos-universal.dmg"
linux_asset="woofer-v${version}-x86_64-unknown-linux-gnu.tar.gz"
windows_x64_asset="woofer-v${version}-x86_64-pc-windows-msvc-setup.exe"
windows_arm64_asset="woofer-v${version}-aarch64-pc-windows-msvc-setup.exe"

for asset in "$macos_asset" "$linux_asset" "$windows_x64_asset" "$windows_arm64_asset"; do
    [[ -s "$dist/$asset" ]] || fail "missing or empty release asset: $asset"
done

macos_sha256="$(checksum_for "$macos_asset")"
linux_sha256="$(checksum_for "$linux_asset")"
windows_x64_sha256="$(checksum_for "$windows_x64_asset")"
windows_arm64_sha256="$(checksum_for "$windows_arm64_asset")"

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
template_dir="$repo_root/packaging"

render() {
    local template=$1
    local destination=$2
    shift 2
    local temp
    [[ -f "$template" ]] || fail "missing package template: $template"
    mkdir -p "$(dirname "$destination")"
    temp="$(mktemp "${destination}.XXXXXX")"
    trap 'rm -f "$temp"' RETURN
    if (($# > 0)); then
        sed "$@" "$template" > "$temp"
    else
        sed -e '' "$template" > "$temp"
    fi
    mv "$temp" "$destination"
    trap - RETURN
}

homebrew_dir="$output_dir/homebrew/Casks"
aur_dir="$output_dir/aur"
winget_dir="$output_dir/winget/manifests/k/kreatzzz/Woofer/$version"

render "$template_dir/homebrew/Casks/woofer.rb.in" \
    "$homebrew_dir/woofer.rb" \
    -e "s/__VERSION__/$version/g" \
    -e "s/__MACOS_SHA256__/$macos_sha256/g"

render "$template_dir/aur/PKGBUILD.in" \
    "$aur_dir/woofer/PKGBUILD" \
    -e "s/__VERSION__/$version/g" \
    -e "s/__LINUX_SHA256__/$linux_sha256/g"

render "$template_dir/aur/PKGBUILD-git.in" \
    "$aur_dir/woofer-git/PKGBUILD"

render "$template_dir/winget/kreatzzz.Woofer.yaml.in" \
    "$winget_dir/kreatzzz.Woofer.yaml" \
    -e "s/__VERSION__/$version/g"

render "$template_dir/winget/kreatzzz.Woofer.installer.yaml.in" \
    "$winget_dir/kreatzzz.Woofer.installer.yaml" \
    -e "s/__VERSION__/$version/g" \
    -e "s/__WINDOWS_X64_SHA256__/$windows_x64_sha256/g" \
    -e "s/__WINDOWS_ARM64_SHA256__/$windows_arm64_sha256/g"

render "$template_dir/winget/kreatzzz.Woofer.locale.en-US.yaml.in" \
    "$winget_dir/kreatzzz.Woofer.locale.en-US.yaml" \
    -e "s/__VERSION__/$version/g"

printf '%s\n' "$output_dir"
